# Generated by Django 4.1 on 2022-09-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='winner',
            field=models.CharField(
                choices=[('B', 'Black'), ('W', 'White'), ('U', 'Undecided')],
                default='U',
                max_length=1,
            ),
        ),
    ]
