# Generated by Django 4.1 on 2022-08-31 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['move']},
        ),
    ]
