# Generated by Django 4.1.1 on 2022-10-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='board_size',
            field=models.IntegerField(choices=[(9, '9x9'), (13, '13x13'), (19, '19x19')]),
        ),
    ]
