import "/record/list.ts";
import "/record/create.ts";
import "/record/update.ts";
import "/record/get.ts";
import "/record/play.ts";
import "/record/delete.ts";
import "/record/pass.ts";
import "/record/undo.ts";
import "/record/download.ts";
