name:                go-recordkeeper
version:             0.1.0.0
github:              "dchiquito/go-recordkeeper"
license:             BSD3
author:              "Daniel Chiquito"
maintainer:          "daniel.chiquito@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dchiquito/go-recordkeeper#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64
- bytestring
- containers
- email-validate
- hasql
- hasql-pool
- hasql-th
- http-types
- jose
- lens
- mtl
- password
- random
- resource-pool
- scotty >= 0.12
- text
- time
- utf8-string
- vector
- wai
- wai-extra
# - warp

ghc-options:
- -j1
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# Global language flags
- -XTemplateHaskell
- -XOverloadedStrings
- -XDuplicateRecordFields
- -XNamedFieldPuns
- -XQuasiQuotes

library:
  source-dirs: src

executables:
  go-recordkeeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-recordkeeper

tests:
  go-recordkeeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-recordkeeper
    - hspec
    - http-client
    - http-types
    - servant-client
    - QuickCheck
