name: Deno
on:
  push:
    paths:
      - 'server/deno/**'
      - 'test/**'
      - '.github/workflows/deno.yml'
jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/deno
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33
      - name: Run deno lint
        run: deno lint
      - name: Run deno check
        run: deno check src/main.ts
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   needs: linting
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: default
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432
  #   defaults:
  #     run:
  #       working-directory: server/deno
  #   env:
  #     POSTGRES_NAME: default
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_HOST: localhost
  #     GOBAN_DEVELOPMENT: true
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3
  #     - name: Setup Deno
  #       uses: denoland/setup-deno@v1
  #       with:
  #         deno-version: v1.33
  #     - name: Run deno lint
  #       run: deno lint
  #     # TODO no tests

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        shell: bash
        working-directory: test
    env:
      POSTGRES_NAME: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      GOBAN_DEVELOPMENT: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Python and Poetry
        uses: ITProKyle/action-setup-python@v0.3.0
        with:
          python-version: 3.11
          # poetry 1.4.0 fails to install FastAPI
          poetry-version: 1.3.2
          poetry-install: false
      - name: Install tests
        shell: bash
        run: poetry install
      - name: Run tests
        shell: bash
        run: poetry run test -- -k "deno"
