name: Django
on:
  push:
    paths:
      - 'server/django/**'
      - 'test/**'
      - '.github/workflows/django.yml'
jobs:
  tox:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: default
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: server/django
    env:
      POSTGRES_NAME: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      GOBAN_DEVELOPMENT: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox

  integration-tests:
    runs-on: ubuntu-latest
    needs: tox
    defaults:
      run:
        shell: bash
        working-directory: test
    env:
      POSTGRES_NAME: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      GOBAN_DEVELOPMENT: true
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Python and Poetry
        uses: ITProKyle/action-setup-python@v0.3.0
        with:
          python-version: 3.11
          # poetry 1.4.0 fails to install FastAPI
          poetry-version: 1.3.2
          poetry-install: false
      - name: Install tests
        run: poetry install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and cache django
        uses: docker/build-push-action@v4
        with:
          context: server/django
          push: false
          load: true
          cache-from: type=gha,scope=django
          cache-to: type=gha,scope=django,mode=min
      - name: Build and cache fastapi
        uses: docker/build-push-action@v4
        with:
          context: server/fastapi
          push: false
          load: true
          cache-from: type=gha,scope=fastapi
          cache-to: type=gha,scope=fastapi,mode=min
      - name: Build and cache haskell
        uses: docker/build-push-action@v4
        with:
          context: server/haskell
          push: false
          load: true
          cache-from: type=gha,scope=haskell
          cache-to: type=gha,scope=haskell,mode=min
      - name: Build and cache rust
        uses: docker/build-push-action@v4
        with:
          context: server/rust
          push: false
          load: true
          cache-from: type=gha,scope=rust
          cache-to: type=gha,scope=rust,mode=min
      - name: Build and cache deno
        uses: docker/build-push-action@v4
        with:
          context: server/deno
          push: false
          load: true
          cache-from: type=gha,scope=deno
          cache-to: type=gha,scope=deno,mode=min
      - name: Build and cache kotlin
        uses: docker/build-push-action@v4
        with:
          context: server/kotlin
          push: false
          load: true
          cache-from: type=gha,scope=kotlin
          cache-to: type=gha,scope=kotlin,mode=min
      - name: Build all docker compose images
        run: docker compose build
      - name: Run tests
        run: poetry run test -- -k "django" || exit 1

