name: FastAPI integration tests
on:
  push:
    paths:
      - 'server/fastapi/**'
      - 'test/**'
      - '.github/workflows/fastapi-integration-tests.yml'
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install tests
        shell: bash
        working-directory: test
        run: |
          cp .env.template .env
          # Required to export all the values in the .env file
          set -a
          source .env
          set +a
          # poetry 1.4.0 fails to install FastAPI
          pip install "poetry==1.3.2"
          poetry install
      - name: Run tests
        shell: bash
        working-directory: test
        run: poetry run test -- -k "fastapi"
