name: FastAPI integration tests
on:
  push:
    paths:
      - 'server/fastapi/**'
      - 'test/**'
      - '.github/workflows/fastapi-integration-tests.yml'
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Python and Poetry
        uses: ITProKyle/action-setup-python@v0.3.0
        with:
          python-version: 3.11
          # poetry 1.4.0 fails to install FastAPI
          poetry-version: 1.3.2
          poetry-install: false
      - name: Install tests
        shell: bash
        working-directory: test
        run: |
          cp .env.template .env
          # Required to export all the values in the .env file
          set -a
          source .env
          set +a
          poetry install
      - name: Run tests
        shell: bash
        working-directory: test
        run: |
          # Required to export all the values in the .env file
          set -a
          source .env
          set +a
          set -e
          poetry run test -- -k "fastapi"
