name: Haskell
on:
  push:
    paths:
      - 'server/haskell/**'
      - 'test/**'
      - '.github/workflows/haskell.yml'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server/haskell
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Haskell
        id: setup
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup.outputs.stack-root }}
            ${{ steps.setup.outputs.cabal-store }}
          key: ${{ hashFiles('server/haskell/go-recordkeeper.cabal', 'server/haskell/stack.yaml', 'server/haskell/stack.yaml.lock', 'server/haskell/package.yaml') }}
      - name: Build
        run: stack build
      - name: Run unit tests
        run: stack test
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        shell: bash
        working-directory: test
    env:
      POSTGRES_NAME: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      GOBAN_DEVELOPMENT: true
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Python and Poetry
        uses: ITProKyle/action-setup-python@v0.3.0
        with:
          python-version: 3.11
          # poetry 1.4.0 fails to install FastAPI
          poetry-version: 1.3.2
          poetry-install: false
      - name: Install tests
        shell: bash
        run: poetry install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and cache django
        uses: docker/build-push-action@v4
        with:
          context: server/django
          push: false
          load: true
          cache-from: type=gha,scope=django
          cache-to: type=gha,scope=django,mode=min
      - name: Build and cache fastapi
        uses: docker/build-push-action@v4
        with:
          context: server/fastapi
          push: false
          load: true
          cache-from: type=gha,scope=fastapi
          cache-to: type=gha,scope=fastapi,mode=min
      - name: Build and cache haskell
        uses: docker/build-push-action@v4
        with:
          context: server/haskell
          push: false
          load: true
          cache-from: type=gha,scope=haskell
          cache-to: type=gha,scope=haskell,mode=min
      - name: Build and cache rust
        uses: docker/build-push-action@v4
        with:
          context: server/rust
          push: false
          load: true
          cache-from: type=gha,scope=rust
          cache-to: type=gha,scope=rust,mode=min
      - name: Build and cache deno
        uses: docker/build-push-action@v4
        with:
          context: server/deno
          push: false
          load: true
          cache-from: type=gha,scope=deno
          cache-to: type=gha,scope=deno,mode=min
      - name: Build all docker compose images
        run: docker compose build
      - name: Run tests
        shell: bash
        run: poetry run test -- -k "haskell"

