name: Haskell
on:
  push:
    paths:
      - 'server/haskell/**'
      - 'test/**'
      - '.github/workflows/haskell.yml'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server/haskell
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Haskell
        id: setup
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup.outputs.stack-root }}
            ${{ steps.setup.outputs.cabal-store }}
          key: ${{ hashFiles('server/haskell/go-recordkeeper.cabal', 'server/haskell/stack.yaml', 'server/haskell/stack.yaml.lock', 'server/haskell/package.yaml') }}
      - name: Build
        run: stack build
      - name: Run unit tests
        run: stack test
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        shell: bash
        working-directory: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup Python and Poetry
        uses: ITProKyle/action-setup-python@v0.3.0
        with:
          python-version: 3.11
          # poetry 1.4.0 fails to install FastAPI
          poetry-version: 1.3.2
          poetry-install: false
      - name: Install tests
        shell: bash
        run: |
          cp .env.template .env
          # Required to export all the values in the .env file
          set -a
          source .env
          set +a
          poetry install
      - name: Run tests
        shell: bash
        run: |
          # Required to export all the values in the .env file
          set -a &&
          source .env &&
          set +a &&
          set -e &&
          poetry run test -- -k "haskell"

